GET http://localhost:5000

###

GET http://localhost:5000/hello

###

GET http://localhost:5000/message

###
GET http://localhost:5000/systems

###
GET http://localhost:5000/systems/2

###
GET http://localhost:5000/systems/10